project:
  type: website

website:
  title: "spiti_mou_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - map_crime.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



